site_name: Mobile Payments

theme: readthedocs

nav:
  - Introduction: index.md
  - Vodacom M-Pesa: vodacom.md

repo_url: https://github.com/ZendaInnocent/mobile-payments.git

repo_name: GitHub

site_description: An easy way to integrate mobile payments into your web project.

markdown_extensions:
  - admonition

site_author: Innocent Zenda

copyright: Copyright &copy; 2020 Innocent Zenda.
